### PR TITLE
Heartbeat animation - #388

### PR DESCRIPTION
**Pull request by UiCandy**
Added a heartbeat animation as requested in issue #388 with optimized code.

### CODE REVIEW

**Comment by procodeing** [comment]
and once again, i derped out, you can do the same thing with the other part:
@-webkit-keyframes heartbeat {
  0%,10%,20%,65%,75%,85% {
    -webkit-transform: scale3d(1, 1, 1);
    transform: scale3d(1, 1, 1);
  }
 5%,15%,70%,80% {
    -webkit-transform: scale3d(1.05, 1.05, 1.05);
    transform: scale3d(1.05, 1.05, 1.05);
  }
}

**Comment by procodeing** [comment]
sorry I forgot about that other part, but I overlooked it.

**Comment by procodeing** [comment]
also, you dont want to scale the last number, so the fianal result would be:
`@-webkit-keyframes heartbeat {
0%,10%,20%,65%,75%,85% {
-webkit-transform: scale3d(1, 1, 1);
transform: scale3d(1, 1, 1);
}
5%,15%,70%,80% {
-webkit-transform: scale3d(1.05, 1.05,1 );
transform: scale3d(1.05, 1.05, 1);
}
}`

**Comment by UiCandy** [comment]
Thank you for your comments @procodeing, really appreciate it!

**Comment by procodeing** [comment]
youre welcome:)

**Pull request closed without merging**
