### PR TITLE
Heartbeat animation - #388

### PR DESCRIPTION
**Pull request by UiCandy**
Added a heartbeat animation as requested in issue #388 with optimized code.

### CODE REVIEW

**Comment by procodeing** [comment]
hi again, we may have a bit of a glitch. But I think I have figured it out. Whats happing is the same glitch with pulse, which I have fixed in my own pull, but what the problem is is that the animation moves undefind width elements off screen! but the patch is simple, along with some inproved code. again. :d

`@-webkit-keyframes heartbeat {
  0%, 10%, 20%, 65%, 75%, 85% {
    -webkit-transform: scale(1, 1);
    transform: scale(1, 1);
  }
  5%, 15%, 70%, 80% {
    -webkit-transform: scale(1.25, 1.25 );
    transform: scale(1.25, 1.25);
  }
}`

`@keyframes heartbeat {
  0%, 10%, 20%, 65%, 75%, 85% {
    -webkit-transform: scale(1, 1);
    transform: scale(1, 1);
  }
  5%, 15%, 70%, 80% {
    -webkit-transform: scale(1.25, 1.25 );
    transform: scale(1.25, 1.25);
  }
}`

`.heartbeat {
  -webkit-animation-name: heartbeat;
  animation-name: heartbeat;
  -webkit-transform-origin: 0%;
  transform-origin: 0% ;
}`

**Comment by procodeing** [comment]
and also, I think this animation is pretty good! oh, and update the readme.md to include the heartbeat animation in the list of animations. hope I've been of help!

**Comment by UiCandy** [comment]
@procodeing Sure, I've added those commits. : ]
Now I'm going to hope to add some other amazing effects thanks!

**Comment by procodeing** [comment]
YAY

**Pull request closed without merging**
